groupId=io.recruitcrm.geocoding
artifactId=geocoding-package
version=1.0.0-SNAPSHOT
package=io.recruitcrm.geocoding
packageName=Geocoding
packageNameLower=geocoding
packageDescription=RecruitCRM geocoding shared library
springBootVersion=3.5.8
sonarProjectKey=Workforce-Cloud-Tech_geocoding-package
repoUrl=https://github.com/Workforce-Cloud-Tech/geocoding-package
slackChannelId=CHANGE_ME_SLACK_CHANNEL_ID
codeowners=@workforce-cloud-tech/java-platform
